name: Build

on:
  pull_request:
    branches:
      - develop
      - master
      - release
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          branch: master
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-alpha${increment}"
          change_path: "./"
          bump_each_commit: true
          #enable_prerelease_mode: true
          namespace: ""

      - name: output version
        run: |
          echo "Setting version too: ${{ steps.semver.outputs.version }}";
      - run: jq '.version = "${{ steps.semver.outputs.version }}"' src/manifest.json > ./manifest.json && mv ./manifest.json src/manifest.json
      - run: echo "version=${{ steps.semver.outputs.version }} >> $GITHUB_OUTPUT"
        id: version

      - run: bash ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: chrome-v${{ steps.semver.outputs.version }}
          path: dist/packed/chrome.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: firefox-v${{ steps.semver.outputs.version }}
          path: dist/packed/firefox.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: edge-v${{ steps.semver.outputs.version }}
          path: dist/packed/edge.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: chrome-latest
          path: dist/packed/chrome.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: firefox-latest
          path: dist/packed/firefox.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: edge-latest
          path: dist/packed/edge.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7
