name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: semver
        id: semver
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: "v"
          branch: master
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}-rc${increment}"
          change_path: "./"
          bump_each_commit: true
          #enable_prerelease_mode: true
          namespace: ""

      - name: output version
        run: |
          echo "Setting version too: ${{ steps.semver.outputs.version }}";
      - run: jq '.version = "${{ steps.semver.outputs.version }}"' src/manifest.json > ./manifest.json && mv ./manifest.json src/manifest.json
      - run: echo "version=${{ steps.semver.outputs.version }} >> $GITHUB_OUTPUT"
        id: version

      - run: bash ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: v${{ steps.semver.outputs.version }}
          path: dist/packed/*
          if-no-files-found: error
          retention-days: 5

      - uses: actions/upload-artifact@v3
        with:
          name: chrome-v${{ steps.semver.outputs.version }}
          path: dist/packed/chrome.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: firefox-v${{ steps.semver.outputs.version }}
          path: dist/packed/firefox.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: edge-v${{ steps.semver.outputs.version }}
          path: dist/packed/edge.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 5

      - name: Create tag for release
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: "${{ steps.semver.outputs.version }}"
          tag_prefix: "v"
          github_token: "${{ secrets.GH_TOKEN }}"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "v${{ steps.semver.outputs.version }}"
          prerelease: true
          title: "Pre-release v${{ steps.semver.outputs.version }}"
          files: |
            LICENSE.txt
            dist/packed/*.zip
