name: Build and Publish

on:
  push:
    tags:
      - '^v[0-9]+.[0-9]+.[0-9]+$'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: semver
        run: echo "version=${GITHUB_REF#refs/tags/v} >> $GITHUB_OUTPUT"

      - name: output version
        run: |
          echo "Setting version too: ${{ steps.semver.outputs.version }}";
      - run: jq '.version = "${{ steps.semver.outputs.version }}"' src/manifest.json > ./manifest.json && mv ./manifest.json src/manifest.json
      - run: echo "version=${{ steps.semver.outputs.version }} >> $GITHUB_OUTPUT"
        id: version

      - run: bash ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: v${{ steps.semver.outputs.version }}
          path: dist/packed/*
          if-no-files-found: error
          retention-days: 5

      - uses: actions/upload-artifact@v3
        with:
          name: chrome-v${{ steps.semver.outputs.version }}
          path: dist/packed/chrome.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: firefox-v${{ steps.semver.outputs.version }}
          path: dist/packed/firefox.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: edge-v${{ steps.semver.outputs.version }}
          path: dist/packed/edge.v${{ steps.semver.outputs.version }}.zip
          if-no-files-found: error
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 5

  publish-chrome:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dists
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Upload & release Chrome Extension
        uses: mnao305/chrome-extension-upload@3.0.0
        with:
          file-path: dist/packed/chrome.latest.zip
          extension-id: "mgfdapnedjhfmhcaglenpnjaocjpfplj"
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          #publish-target: trustedTesters
          publish: true

  publish-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dists
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Build Firefox Extension
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: dist/unpacked/firefox
          artifacts: dist/packed/
          filename: firefox.latest.unsigned.xpi

      - name: Upload & release Firefox Extension
        uses: kewisch/action-web-ext@v1
        id: firefoxrelease
        with:
          cmd: sign
          source: dist/packed/firefox.latest.unsigned.xpi
          artifacts: dist/packed/
          channel: listed
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}
          timeout: 900000

      - run: rm dist/packed/firefox.latest.unsigned.xpi

      - run: mv ${{ steps.firefoxrelease.outputs.target }} dist/packed/firefox.v${{ needs.build.outputs.version }}.signed.xpi

      - run: cp dist/packed/firefox.v${{ needs.build.outputs.version }}.signed.xpi dist/packed/firefox.latest.signed.xpi

      - uses: actions/upload-artifact@v3
        with:
          name: firefox-v${{ needs.build.outputs.version }}-signed
          path: dist/packed/firefox.v${{ needs.build.outputs.version }}.signed.xpi
